### ISSUE TITLE
ImportError: cannot import name 'API' from 'chromadb.api'

### ISSUE THREAD

**Issue by randywreed** [chroma-core/chroma-migrate#13]
got a message that my chromadb was out of date. Downloaded chroma-migrate and ran. Error occured. This is on a local database.
```
Traceback (most recent call last):
  File "/media/randy/025936B45A234DF9/openai_tts_chatbot/venv_openai_tts_chatbot/bin/chroma-migrate", line 5, in <module>
    from chroma_migrate.cli import run_cli
  File "/media/randy/025936B45A234DF9/openai_tts_chatbot/venv_openai_tts_chatbot/lib/python3.10/site-packages/chroma_migrate/cli.py", line 10, in <module>
    from chroma_migrate.import_clickhouse import migrate_from_clickhouse
  File "/media/randy/025936B45A234DF9/openai_tts_chatbot/venv_openai_tts_chatbot/lib/python3.10/site-packages/chroma_migrate/import_clickhouse.py", line 3, in <module>
    from chromadb.api import API
ImportError: cannot import name 'API' from 'chromadb.api' (/media/randy/025936B45A234DF9/openai_tts_chatbot/venv_openai_tts_chatbot/lib/python3.10/site-packages/chromadb/api/__init__.py)
```
I should note because of https://github.com/chroma-core/chroma/issues/1452 I tried to install directly from github instead of pip but the results were the same.

**Comment by jeffchuber** [comment]
@randywreed do you know what version you were on before? you said the migrate failed - is the output above the error from that?

**Comment by randywreed** [comment]
I actually now think this was an attempt to upgrade and already upgraded db. I'm closing this.
