### ISSUE TITLE
ModuleNotFoundError: No module named 'termios' on Windows 10

### ISSUE THREAD

**Issue by Joseph-Cardwell** [chroma-core/chroma-migrate#6]
>chroma-migrate
<pre>Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\Projects\assistant\venv\Scripts\chroma-migrate.exe\__main__.py", line 4, in <module>
  File "C:\Users\Administrator\Projects\assistant\venv\lib\site-packages\chroma_migrate\cli.py", line 1, in <module>
    from bullet import Bullet, SlidePrompt, Check, Input, YesNo, Numbers
  File "C:\Users\Administrator\Projects\assistant\venv\lib\site-packages\bullet\__init__.py", line 1, in <module>
    from .client import Bullet
  File "C:\Users\Administrator\Projects\assistant\venv\lib\site-packages\bullet\client.py", line 4, in <module>
    from . import utils
  File "C:\Users\Administrator\Projects\assistant\venv\lib\site-packages\bullet\utils.py", line 3, in <module>
    import tty, termios
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\tty.py", line 5, in <module>
    from termios import *
ModuleNotFoundError: No module named 'termios'
</pre>

in  bullet/utils.py line 3 it import tty and it's dependency termios.

in line 5 of tty termios is imported again but returns empty as it returns null on sys.platform !="wind32", essentially disabling the migrate script on windows systems.
 
`import sys
from _typeshed import FileDescriptorLike
from typing import Any
from typing_extensions import TypeAlias

if sys.platform != "win32":
    _Attr: TypeAlias = list[int | list[bytes | int]]

    # TODO constants not really documented
    B0: int
    B1000000: `int`

**Comment by HammadB** [comment]
Hi @Joseph-Cardwell, sorry about this. It seems like Bullet does not support windows, we will have to modify the CLI to support windows. In the meantime you can look at the examples in examples/ to see how to run the code without requiring bullet. Let me know if that works for you, and we'll work on getting something working for windows in the meantime!

**Comment by Joseph-Cardwell** [comment]
no worries, I'll sort my setup, just wanted to give you guys the heads up. 

Thanks for such a great product!

**Comment by HammadB** [comment]
Hi @Joseph-Cardwell ! Thanks for the kind words, I've patched the underlying dependency on bullet to be windows compatible and issued chroma_migrate=0.0.4, that should work on windows! Let me know if that works for you! Closing for now as this should be resolved but feel free to reopen.
