### ISSUE TITLE
TypeError: object of type 'float' has no len()

### ISSUE THREAD

**Issue by andrewshvv** [chroma-core/chroma-migrate#9]
Q: What was the previous ChromaDB version?
- `chromadb==0.3.29`

Q: What is the current ChromaDB version?
- `chromadb = "^0.4.2"`

Q: On which versions of chroma-migrate do you see this issue?
- `chroma-migrate = "^0.0.5"`, or
- commit hash: `f188d084eda90a73cf804beac7c8164b6fdd8e97`

Q: How can we replicate the issue?
- Download DB and migrate, [chroma.zip](https://github.com/chroma-core/chroma-migrate/files/12109813/chroma.zip)

Q: What was your cli path?
- DuckDB (You run chroma and save files to a persist_directory)
- Files I can use on my local machine with chroma, or upload to a remote server that runs chroma
- What is the path to the persist directory your data is currently stored in?[./chroma] - Clicked enter
- What is the path you would like your data to be stored in?[./chroma_migrated] - Clicked enter

Q: What is trace output?
```
(JobSearch) ➜  JobSearch git:(main) ✗ chroma-migrate
...
...
...
Traceback (most recent call last):
  File "/Users/andrey/opt/anaconda3/envs/JobSearch/bin/chroma-migrate", line 8, in <module>
    sys.exit(run_cli())
             ^^^^^^^^^
  File "/Users/andrey/opt/anaconda3/envs/JobSearch/lib/python3.11/site-packages/chroma_migrate/cli.py", line 130, in run_cli
    migrate_from_duckdb(api, persist_directory)
  File "/Users/andrey/opt/anaconda3/envs/JobSearch/lib/python3.11/site-packages/chroma_migrate/import_duckdb.py", line 77, in migrate_from_duckdb
    collection.add(id, embedding, metadata, document)
  File "/Users/andrey/opt/anaconda3/envs/JobSearch/lib/python3.11/site-packages/chromadb/api/models/Collection.py", line 96, in add
    ids, embeddings, metadatas, documents = self._validate_embedding_set(
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrey/opt/anaconda3/envs/JobSearch/lib/python3.11/site-packages/chromadb/api/models/Collection.py", line 379, in _validate_embedding_set
    if documents is not None and len(documents) != len(ids):
                                 ^^^^^^^^^^^^^^
TypeError: object of type 'float' has no len()
```

**Comment by HammadB** [comment]
We just released 0.0.6 which should fix this issue!
